/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('antdv-next')['Affix']
    AAlert: typeof import('antdv-next')['Alert']
    AAnchor: typeof import('antdv-next')['Anchor']
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    AAvatarGroup: typeof import('antdv-next')['AvatarGroup']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AFlex: typeof import('antdv-next')['Flex']
    AInput: typeof import('antdv-next')['Input']
    AMenu: typeof import('antdv-next')['Menu']
    APopover: typeof import('antdv-next')['Popover']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARow: typeof import('antdv-next')['Row']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASpace: typeof import('antdv-next')['Space']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATypography: typeof import('antdv-next')['Typography']
    ATypographyParagraph: typeof import('antdv-next')['TypographyParagraph']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAffix: typeof import('antdv-next')['Affix']
  const AAlert: typeof import('antdv-next')['Alert']
  const AAnchor: typeof import('antdv-next')['Anchor']
  const AApp: typeof import('antdv-next')['App']
  const AAvatar: typeof import('antdv-next')['Avatar']
  const AAvatarGroup: typeof import('antdv-next')['AvatarGroup']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const ACol: typeof import('antdv-next')['Col']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AEmpty: typeof import('antdv-next')['Empty']
  const AFlex: typeof import('antdv-next')['Flex']
  const AInput: typeof import('antdv-next')['Input']
  const AMenu: typeof import('antdv-next')['Menu']
  const APopover: typeof import('antdv-next')['Popover']
  const ARadio: typeof import('antdv-next')['Radio']
  const ARadioGroup: typeof import('antdv-next')['RadioGroup']
  const ARow: typeof import('antdv-next')['Row']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ASpace: typeof import('antdv-next')['Space']
  const ATabPane: typeof import('antdv-next')['TabPane']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATag: typeof import('antdv-next')['Tag']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const ATypography: typeof import('antdv-next')['Typography']
  const ATypographyParagraph: typeof import('antdv-next')['TypographyParagraph']
  const ATypographyText: typeof import('antdv-next')['TypographyText']
  const ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}